/**
 * Tree project
 * Mobile API documentation
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.Check
import io.swagger.client.model.Find
import io.swagger.client.model.SetPwd
import io.swagger.client.model.SignIn
import io.swagger.client.model.SignUp
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object AuthApi {

  /**
   * 
   * Expected answers:
   *   code 200 :  (Success. Will return user data)
   *   code 401 :  (User not found or wrong email/password)
   * 
   * @param body 
   */
  def resetCheckPost(body: Check): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://virtserver.swaggerhub.com/Gsol/tree/1", "/reset/check", "application/json")
      .withBody(body)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](401)
        /**
   * 
   * Expected answers:
   *   code 200 :  (Success. Will return user data)
   *   code 401 :  (User not found or wrong email/password)
   * 
   * @param body 
   */
  def resetFindPost(body: Find): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://virtserver.swaggerhub.com/Gsol/tree/1", "/reset/find", "application/json")
      .withBody(body)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](401)
        /**
   * 
   * Expected answers:
   *   code 200 :  (Success. Will return user data)
   *   code 401 :  (User not found or wrong email/password)
   * 
   * Available security schemes:
   *   Bearer (apiKey)
   * 
   * @param body 
   */
  def resetSetPasswordPost(body: SetPwd)(implicit apiKey: ApiKeyValue): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://virtserver.swaggerhub.com/Gsol/tree/1", "/reset/setPassword", "application/json")
      .withApiKey(apiKey, "Authorization", HEADER)
      .withBody(body)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](401)
        /**
   * 
   * Expected answers:
   *   code 200 :  (Success. Will return user data)
   *   code 401 :  (User not found or wrong email/password)
   * 
   * @param body 
   */
  def signInPost(body: SignIn): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://virtserver.swaggerhub.com/Gsol/tree/1", "/signIn", "application/json")
      .withBody(body)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](401)
        /**
   * 
   * Expected answers:
   *   code 200 :  (Success. Will return user data)
   *   code 401 :  (User not found or wrong email/password)
   * 
   * @param body 
   */
  def signUpPost(body: SignUp): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://virtserver.swaggerhub.com/Gsol/tree/1", "/signUp", "application/json")
      .withBody(body)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](401)
      

}

