/**
 * Tree project
 * Mobile API documentation
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class SignUp (
  email: Option[String] = None,
  password: Option[String] = None,
  /* Not required */
  fullName: Option[String] = None,
  name: Option[String] = None,
  `type`: Option[SignUpEnums.`Type`] = None
) extends ApiModel

object SignUpEnums {

  type `Type` = `Type`.Value
  object `Type` extends Enumeration {
    val INDIVIDUAL = Value("INDIVIDUAL")
    val SCHOOL = Value("SCHOOL")
    val NGO = Value("NGO")
    val COMMUNITY = Value("COMMUNITY")
  }

}

